version: '3.8'

services:
  db:
    image: mysql:8
    container_name: eunji-docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 8963
      MYSQL_DATABASE: pyweb
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  web:
    build: .
    container_name: eunji-web
    ports:
      - "4000-4050:4000-4050"
    volumes:
      - .:/workspace
    depends_on:
      - db
